[package]
name = "r-mmdc"
version = "0.1.0"
authors = ["blatzfab <fabian.blatz@hansgrohe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.18.0"
regex = "1"

